-- Continue inserting styles from CSV data (part 6)
INSERT INTO styles (name, slug, thumb_url, json) VALUES
('Opal Dreamscape Cosmic Glamour Aesthetic', 'opal-dreamscape-cosmic-glamour-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_opal_dreamscape_cosmic_glamour_aesthetic.png', '{}'),
('Orange Vibe Aesthetic', 'orange-vibe-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_orange_vibe_aesthetic.png', '{}'),
('Paint Sci Fi Aesthetic', 'paint-sci-fi-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_paint_sci_fi_aesthetic.png', '{}'),
('Pastel Fantasy Sculptural Surrealism Aesthetic', 'pastel-fantasy-sculptural-surrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_pastel_fantasy_sculptural_surrealism_aesthetic.png', '{}'),
('Pastel Lux Softdivinity Aesthetic Detailed', 'pastel-lux-softdivinity-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_pastel_lux_softdivinity_aesthetic_detailed.png', '{}'),
('Pastel Translucent Aesthetic', 'pastel-translucent-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_pastel_translucent_aesthetic.png', '{}'),
('Pastel Vaporbaroque Collagecore Aesthetic Detailed', 'pastel-vaporbaroque-collagecore-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_pastel_vaporbaroque_collagecore_aesthetic_detailed.png', '{}'),
('Pastoral Melancholia Oilrealism Aesthetic', 'pastoral-melancholia-oilrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_pastoral_melancholia_oilrealism_aesthetic.png', '{}'),
('Pearlescent Dreamfruit Romance Aesthetic', 'pearlescent-dreamfruit-romance-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_pearlescent_dreamfruit_romance_aesthetic.png', '{}'),
('Perplexity Aesthetic', 'perplexity-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_perplexity_aesthetic.png', '{}'),
('Pink Pop Surrealism Aesthetic Detailed', 'pink-pop-surrealism-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_pink_pop_surrealism_aesthetic_detailed.png', '{}'),
('Pixar Poly Softlight Aesthetic', 'pixar-poly-softlight-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_pixar_poly_softlight_aesthetic.png', '{}'),
('Pixel Dispersion Aesthetic', 'pixel-dispersion-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_pixel_dispersion_aesthetic.png', '{}'),
('Pixel Stipple Surrealist Pop Aesthetic', 'pixel-stipple-surrealist-pop-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_pixel_stipple_surrealist_pop_aesthetic.png', '{}'),
('Post Apocalyptic Graphic Saga Aesthetic', 'post-apocalyptic-graphic-saga-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_post_apocalyptic_graphic_saga_aesthetic.png', '{}'),
('Prismatic Dreamcore Aesthetic Detailed', 'prismatic-dreamcore-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_prismatic_dreamcore_aesthetic_detailed.png', '{}'),
('Prismatic Fashion Editorial Aesthetic', 'prismatic-fashion-editorial-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_prismatic_fashion_editorial_aesthetic.png', '{}'),
('Projection Surrealist Sci Cinema Aesthetic', 'projection-surrealist-sci-cinema-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_projection_surrealist_sci_cinema_aesthetic.png', '{}'),
('Psychedelic 70s Photomontage Pop Aesthetic', 'psychedelic-70s-photomontage-pop-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_psychedelic_70s_photomontage_pop_aesthetic.png', '{}'),
('Psychedelic Surrealism Aesthetic', 'psychedelic-surrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_psychedelic_surrealism_aesthetic.png', '{}');
