-- Continue inserting styles from CSV data (part 2)
INSERT INTO styles (name, slug, thumb_url, json) VALUES
('Cinematic Space Aesthetic', 'cinematic-space-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_cinematic_space_aesthetic.png', '{}'),
('Classical Pastoral Surrealism Aesthetic', 'classical-pastoral-surrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_classical_pastoral_surrealism_aesthetic.png', '{}'),
('Collage Realism Surrealism Aesthetic', 'collage-realism-surrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_collage_realism_surrealism_aesthetic.png', '{}'),
('Cosmic Apocalypse Sci Fi Aesthetic', 'cosmic-apocalypse-sci-fi-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_cosmic_apocalypse_sci_fi_aesthetic.png', '{}'),
('Cosmic Desert Synthdust Aesthetic', 'cosmic-desert-synthdust-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_cosmic_desert_synthdust_aesthetic.png', '{}'),
('Cosmic Mythrealism', 'cosmic-mythrealism', 'https://assets-themes.s3.amazonaws.com/generations/style_cosmic_mythrealism.png', '{}'),
('Cosmic Vapor Dreamwave Aesthetic', 'cosmic-vapor-dreamwave-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_cosmic_vapor_dreamwave_aesthetic.png', '{}'),
('Cotton Candy Surrealism Aesthetic', 'cotton-candy-surrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_cotton_candy_surrealism_aesthetic.png', '{}'),
('Crayon Pastel Diary Aesthetic', 'crayon-pastel-diary-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_crayon_pastel_diary_aesthetic.png', '{}'),
('Cyber Red Noir Aesthetic Detailed', 'cyber-red-noir-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_cyber_red_noir_aesthetic_detailed.png', '{}'),
('Cyber Synth Cinematic Portraits Aesthetic', 'cyber-synth-cinematic-portraits-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_cyber_synth_cinematic_portraits_aesthetic.png', '{}'),
('Digital Pointillism Aesthetic', 'digital-pointillism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_digital_pointillism_aesthetic.png', '{}'),
('Dreamgold Etherealsheen Opulentsurrealism Aesthetic', 'dreamgold-etherealsheen-opulentsurrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_dreamgold_etherealsheen_opulentsurrealism_aesthetic.png', '{}'),
('Dreamy Bubbly Aesthetic', 'dreamy-bubbly-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_dreamy_bubbly_aesthetic_.png', '{}'),
('Electroluminal Epicpop Aesthetic', 'electroluminal-epicpop-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_electroluminal_epicpop_aesthetic.png', '{}'),
('Etched Renaissance Aesthetic Detailed', 'etched-renaissance-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_etched_renaissance__aesthetic_detailed.png', '{}'),
('Ethereal Aquatic Glow Fashion Aesthetic', 'ethereal-aquatic-glow-fashion-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_ethereal_aquatic_glow_fashion_aesthetic.png', '{}'),
('Etherpunk Bioholo Aesthetic', 'etherpunk-bioholo-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_etherpunk_bioholo_aesthetic.png', '{}'),
('Filigree Fractal Surrealism Aesthetic', 'filigree-fractal-surrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_filigree_fractal_surrealism_aesthetic.png', '{}'),
('Flat Surreal Pop Animorphism Aesthetic', 'flat-surreal-pop-animorphism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_flat_surreal_pop_animorphism_aesthetic.png', '{}');
