-- Continue inserting styles from CSV data (part 4)
INSERT INTO styles (name, slug, thumb_url, json) VALUES
('Hyperplastic Surrealism Aesthetic', 'hyperplastic-surrealism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_hyperplastic_surrealism_aesthetic.png', '{}'),
('Iridescent Fantasy Aesthetic', 'iridescent-fantasy-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_iridescent_fantasy_aesthetic.png', '{}'),
('Iridescent Lowpoly Vapor Icons Aesthetic', 'iridescent-lowpoly-vapor-icons-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_iridescent_lowpoly_vapor_icons_aesthetic.png', '{}'),
('Iridescent Sci Fi Decay Aesthetic', 'iridescent-sci-fi-decay-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_iridescent_sci_fi_decay_aesthetic.png', '{}'),
('Jellycore Hypermaterial Gloss Aesthetic', 'jellycore-hypermaterial-gloss-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_jellycore_hypermaterial_gloss_aesthetic.png', '{}'),
('Luminous Noir Mythrealism Aesthetic Detailed', 'luminous-noir-mythrealism-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_luminous_noir_mythrealism_aesthetic_detailed.png', '{}'),
('Midcentury Dreamsurrealism Aesthetic Detailed', 'midcentury-dreamsurrealism-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_midcentury_dreamsurrealism_aesthetic_detailed.png', '{}'),
('Midcentury Graphic Modernist Aesthetic', 'midcentury-graphic-modernist-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_midcentury_graphic_modernist_aesthetic.png', '{}'),
('Midnight Neon Revenant Aesthetic', 'midnight-neon-revenant-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_midnight_neon_revenant_aesthetic.png', '{}'),
('Minimal Grid Pop Aesthetic Detailed', 'minimal-grid-pop-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_minimal_grid_pop_aesthetic_detailed.png', '{}'),
('Modernist Monochrome Realism Aesthetic', 'modernist-monochrome-realism-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_modernist_monochrome_realism_aesthetic.png', '{}'),
('Modular Flattech Aesthetic', 'modular-flattech-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_modular_flattech_aesthetic.png', '{}'),
('Mono Pixel Aesthetic', 'mono-pixel-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_mono_pixel_aesthetic.png', '{}'),
('Moody Surreal Aesthetic', 'moody-surreal-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_moody_surreal_aesthetic.png', '{}'),
('Morph Vgart Aesthetic', 'morph-vgart-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_morph_vgart_aesthetic.png', '{}'),
('Mystic Monochrome Aesthetic', 'mystic-monochrome-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_mystic_monochrome_aesthetic.png', '{}'),
('Necrotech Glowcore Aesthetic', 'necrotech-glowcore-aesthetic', 'https://assets-themes.s3.amazonaws.com/generations/style_necrotech_glowcore_aesthetic.png', '{}'),
('Neo Grindhouse Splatterpop Aesthetic Detailed', 'neo-grindhouse-splatterpop-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_neo_grindhouse_splatterpop_aesthetic_detailed.png', '{}'),
('Neo Mystic Flatpop Aesthetic Detailed', 'neo-mystic-flatpop-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_neo_mystic_flatpop_aesthetic_detailed.png', '{}'),
('Neo Nihonga Acid Pastoralism Aesthetic Detailed', 'neo-nihonga-acid-pastoralism-aesthetic-detailed', 'https://assets-themes.s3.amazonaws.com/generations/style_neo_nihonga_acid_pastoralism_aesthetic_detailed.png', '{}');
